# UCL, University College London: Myriad + SGE
snippets: "/snippets_library/UCL_Myriad_sge"

local:
  prompt: "[user@laptop ~]$"

remote:
  name: "Myriad"
  login: "myriad.rc.ucl.ac.uk"
  host: "login12.myriad.ucl.ac.uk"
  node: node-d00a-005
  location: "University College London"
  homedir: "/home"
  user: "yourUsername"
  prompt: "[yourUsername@login12 ~]$ "
  bash_shebang: "#!/bin/bash -l"

sched:
  name: "SGE"
  submit:
    name: "qsub"
    options: ""
    iopt: ""
  status: "qstat"
  flag:
    user: "-u yourUsername"
    interactive: "-l mem=512M,h_rt=2:00:00"
    name: "-N"
    histdetail: "-j"
    time: "-l h_rt="
    queue: "-q"
  del: "qdel"
  interactive: "qrsh"
  info: "qhost"
  comment: "#$ "
  hist: "jobhist"
  hist_filter: ""
  bash_shebang: "#!/bin/bash -l"

episode_order:
  - 10-hpc-intro
  - 11-connecting
  - 12-cluster
  - 13-scheduler
  - 14-environment-variables
  - 15-modules
  - 16-transferring-files
  - 17-parallel
  - 18-resources
  - 19-responsibility
