# NIST Blackbird cluster snippets
---
snippets: "/snippets_library/NIST_Blackbird_slurm"

local:
  prompt: "user@laptop:~$"
  bash_shebang: "#!/usr/bin/bash"

remote:
  name: "Blackbird"
  login: "blackbird.nist.gov"
  host: "blackbird"
  node: "bb001"
  location: "National Institute of Standards and Technology"
  homedir: "/home"
  user: "abc"
  prompt: "abc@blackbird:~$"
  bash_shebang: "#!/bin/bash"

sched:
  name: "Slurm"
  submit:
    name: "sbatch"
    options: "--partition=batch"
  queue:
    debug: "batch"
    testing: "batch"
  status: "squeue"
  flag:
    user: "-u abc"
    interactive: ""
    histdetail: "--format=JobName,Submit,Start,State,ReqCPUS,Reserved,Elapsed,MaxRSS -j"
    name: "-J"
    time: "-t"
    queue: "-p"
    partition: "-p batch"
  del: "scancel"
  interactive: "srun"
  info: "sinfo"
  comment: "#SBATCH"
  hist: "sacct -u abc"
  hist_filter: ""

episode_order:
  - 10-hpc-intro
  - 11-connecting
  - 12-cluster
  - 13-scheduler
  - 14-environment-variables
  - 16-transferring-files
  - 17-parallel
  - 18-resources
  - 19-responsibility
